### ISSUE TITLE
Use os.output instead of writing in a file

### ISSUE THREAD

**Issue by HadrienRenaud** [YoPox/mdbg#10]
Instead of making a big string `ouput` and then writing it in the file, we could use `print` to write it progressively.

We could use 2 syntaxes :
- changing `os.output` as describted [here](https://docs.python.org/3.6/library/sys.html#sys.stdout) : 
```python
content = 'blabla' 
file = open('output.tex', 'w') # opening file
os.output = file # changing ouput of print
print(content) # writing in file
os.output = os.__output__ # back to normal
```
- Or, as described [here](http://stefaanlippens.net/redirect_python_print/) :
```python
content = 'balbla'
file = open('output.tex','w')
print(content) >>file
```

The inconvenient of the second method is that you have to have file in the local environnement each time you call print. The first use more powerful (= riskier) tools.

**Comment by elidiot18** [comment]
Yes and no : as the program is recursive, inner parts should be parsed before large sections which makes it impossible to write in the file little by little.

**Comment by HadrienRenaud** [comment]
All right.
