### ISSUE TITLE
Repare center environment

### ISSUE THREAD

**Issue by yopox** [YoPox/mdbg#12]
The center environment (bloc between `(((` and `)))`) does not work as expected.
The mdbg code from the centered bloc is considered as raw text thus I can't center my beautiful graphs easily 🌵

**Comment by elidiot18** [comment]
Should we say that this issue is closed ? Or your solution is meant to be temporary ?

**Comment by yopox** [comment]
As you wish ! If you're satisfied with two regexp instead of one let's close.

**Comment by elidiot18** [comment]
Well it's okay but you'd rather put something like `(?<=\n)[)]3` otherwise $f(g(h(x)))$ is going to be parsed !

**Comment by yopox** [comment]
Yes it was a quick workaround haha
Please update the regexp if the new one works !
