### ISSUE TITLE
New lines and line breaks

### ISSUE THREAD

**Issue by elidiot18** [YoPox/mdbg#5]
One of us has proposed that we sould convert line breaks from the mdbg document to '\\' in LaTeX.
However, we can't put a naive `re.sub(r'\n', r'\\\\\n', text)`
I tried smth : <http://pastebin.com/A2fzJuY0>

It consists in adding a 'pseudo-line' block and parsing it like other blocks, with an appropriated function.

What do you think of it ?

**Comment by HadrienRenaud** [comment]
> However, we can't put a naive `re.sub(r'\n', r'\\\\\n', text)`

Why? 

And why convert `\n` to `//` ? 
Isn't `//` a bad practice in LaTeX? As indicated [here](https://fr.sharelatex.com/learn/Line_breaks_and_blank_spaces) :

> Breaking the document flow in LATEX is not recommended

We shouldn't use in LaTeX not recommended signs.

**Comment by elidiot18** [comment]
> Why?

Because there're many `\n` in the document which souldn't replaced by a `\newline` aren't there !

> We shouldn't use in LaTeX not recommended signs.

~~No, it is different.
Breaking the flow is for example using `\break` without putting a `\hfill` before.~~

~~It would just be a way of avoiding to write `<br>` everywhere by detecting where there should be a new line.~~

Ok you're right.
But we still use some `<br>`s so the problem is the same isn't it ?

**Comment by HadrienRenaud** [comment]
Let's consider that `<br>`are the equivalent in HTML of `//` in LaTeX and of `\n\n` in markdown.

**Comment by elidiot18** [comment]
`<br>` is converted to `\newline` so we do break the flow.

**Comment by HadrienRenaud** [comment]
> `<br>` is converted to \newline so we do break the flow.

OK for that. 

Do we define `\n` as a newline in mdbg? Of de we treat it like in markdown and in LaTeX? 

(in md and in LaTeX, 2 new lines in code = a new line printed, a new line in code = nothing printed)

**Comment by elidiot18** [comment]
This is what I propose :

As very often, we can easily forsee the usage of `<br>` we should indeed replace `\n` by `\newline` when it should.

For example, we're not going to replace it if it is followed or preceded by another `\n`.

That's what I did in the example I sent (in which I forgot to put `inline_parse` of `inside` btw)

This sould be done only inside paragraphs of text, that's why I created a new 'block'

If we don't want a line break we could just put four spaces or one tab at the begining of the line what do you think of it ?

**Comment by elidiot18** [comment]
If you want to write some poetry you're probably likely to be in need of this `\newline` aren't you
And in a informatics lesson you're likely to write some short lines which shouldn't be so far one from the other

**Comment by HadrienRenaud** [comment]
I think this isn't a bad idea but why complicating everything?
Why can't we keep it simple?

The simple form wouldn't add more time to the user,  and the code would be more comfortable to correct!

**Comment by elidiot18** [comment]
So you want to keep `<br>` in mdbg ?

I don't think it is a very nice notation but well, if you say so...

In this case couldn't we remplace `<br>` by `/` at the end of a line ?

**Comment by HadrienRenaud** [comment]
No I don't think that it is a good notation 

I don't want any symbol to mark a new line, for me a new line is juste a blank line! 
Like this :

``` mdbg
Some text. 

An other line! 
```

**Comment by elidiot18** [comment]
And if I want to write :

```
Milton! thou shouldst be living at this hour:
England hath need of thee: she is a fen
Of stagnant waters: altar, sword, and pen,
Fireside, the heroic wealth of hall and bower,
Have forfeited their ancient English dower
Of inward happiness. We are selfish men;
Oh! raise us up, return to us again;
And give us manners, virtue, freedom, power.
Thy soul was like a Star, and dwelt apart;
Thou hadst a voice whose sound was like the sea:
Pure as the naked heavens, majestic, free,
So didst thou travel on life's common way,
In cheerful godliness; and yet thy heart
The lowliest duties on herself did lay.
```

What syntax am I going to use ?...

**Comment by elidiot18** [comment]
And if you want to have several lines in one item of an itemize ?

**Comment by HadrienRenaud** [comment]
A blank line between each poetry line! 

I didn't think of that.
Maybe you are right, we should mark / at the end of the line to mark a new line after? To mark no new line after?

**Comment by elidiot18** [comment]
Mark a / at the end of a line to mark no new line? So it wouldn't be at the end of the line would it? ^^

But yeah indeed to mark a new line, it would be fine

**Comment by HadrienRenaud** [comment]
Examples :

``` mdbg
Some text. 

A new line.  /
An other new line. 

- a item 
- an other item
The following of the 2nd item (on the same line) 
- the third item /
The following of the third item on an other line 
```
